# Create an HTML report from results generated by R/01_run_mse.R.

suppressPackageStartupMessages(library(SPASAM.MSE))

project_dir <- normalizePath(file.path(getwd()), mustWork = TRUE)
results_dir <- file.path(project_dir, "output", "mse_results")
report_dir <- file.path(project_dir, "output", "mse_report")

if (!requireNamespace("SPASAM.MSE", quietly = TRUE)) {
  stop(
    "SPASAM.MSE is not installed. Run remotes::install_github(\"lichengxue/SPASAM.MSE\", dependencies = TRUE) first.",
    call. = FALSE
  )
}
if (!file.exists(file.path(results_dir, "run_metadata.rds"))) {
  stop("No MSE results found. Run R/01_run_mse.R before plotting.", call. = FALSE)
}

metadata <- readRDS(file.path(results_dir, "run_metadata.rds"))
strategy_names <- names(metadata$strategies)

load_replicate <- function(strategy_name, replicate_id) {
  result_file <- file.path(results_dir, strategy_name, sprintf("replicate_%03d.rds", replicate_id))
  if (!file.exists(result_file)) {
    stop(sprintf("Missing result: %s", result_file), call. = FALSE)
  }
  readRDS(result_file)
}

mods <- lapply(seq_len(metadata$n_replicates), function(replicate_id) {
  strategy_results <- lapply(strategy_names, load_replicate, replicate_id = replicate_id)
  names(strategy_results) <- strategy_names
  strategy_results
})

dir.create(report_dir, recursive = TRUE, showWarnings = FALSE)
plot_mse_output(
  mods,
  main_dir = project_dir,
  output_dir = "output/mse_report",
  output_format = "html",
  width = 10,
  height = 7,
  dpi = 300,
  col.opt = "D",
  new_model_names = strategy_names,
  base.model = strategy_names[[1]],
  start.years = min(metadata$assessment_years) + 1,
  use.n.years.first = 5,
  use.n.years.last = 5
)

message("MSE report created in: ", report_dir)